apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odoo-operator
  namespace: {{ .Release.Namespace }}
rules:
  # Permissions for managing Odoo custom resources
  - apiGroups: ["bemade.org"]
    resources: ["odooinstances", "gitsyncs", "odoobackupjobs", "odoorestorejobs", "odooupgradejobs", "odooinitjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Permissions for managing status subresources
  - apiGroups: ["bemade.org"]
    resources: ["odooinstances/status", "gitsyncs/status", "odoobackupjobs/status", "odoorestorejobs/status", "odooupgradejobs/status", "odooinitjobs/status"]
    verbs: ["get", "update", "patch"]

  # Permissions for managing core Kubernetes resources
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Permissions for managing apps resources
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Permissions for scaling deployments
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "update", "patch"]

  # Permissions for managing batch resources
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Permissions for managing batch status subresources
  - apiGroups: ["batch"]
    resources: ["jobs/status", "cronjobs/status"]
    verbs: ["get", "update", "patch"]

  # Permissions for managing networking resources
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Permissions for managing namespaces
  - apiGroups: [""]
    resources: ["namespaces","status"]
    verbs: ["get", "list", "watch"]

  # Permissions for customresourcedefinitions
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]

  # Permissions for certificates
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]

  # Validation and mutation webhook management
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
    verbs: ["create", "patch", "get", "list", "update", "delete"]