apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ .Release.Name }}-webhook.{{ .Release.Namespace }}.svc
    - {{ .Release.Name }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.webhook.certIssuer }}
  secretName: {{ .Release.Name }}-webhook-cert
