apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-webhook-cert
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - Bemade
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
  dnsNames:
    - {{ .Release.Name }}-webhook
    - {{ .Release.Name }}-webhook.{{ .Release.Namespace }}
    - {{ .Release.Name }}-webhook.{{ .Release.Namespace }}.svc
    - {{ .Release.Name }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ .Release.Name }}-webhook-issuer
    kind: Issuer