apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}-validating-webhook
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Release.Name }}-webhook-cert
webhooks:
  - name: vodooinstance.kb.io
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ .Release.Name }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-bemade-org-v1alpha1-odooinstance
        port: 443
    rules:
      - apiGroups: ["bemade.org"]
        apiVersions: ["v1alpha1"]
        operations: ["UPDATE"]
        resources: ["odooinstances"]
        scope: Namespaced
    failurePolicy: Fail
    sideEffects: None
