apiVersion: v2
name: odoo-operator
description: A Kubernetes operator for managing Odoo instances
type: application
version: 0.13.7
appVersion: 0.13.7
keywords:
  - odoo
  - operator
  - kubernetes
  - bemade
home: https://github.com/bemade/odoo-operator
maintainers:
  - name: Bemade Inc.
    email: marc@bemade.org
    url: https://bemade.org
sources:
  - https://github.com/bemade/odoo-operator
