{{- if not .Values.postgresClustersSecretRef.name -}}
  {{- fail "postgresClustersSecretRef.name is required. Create a secret with clusters.yaml and reference it here." -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        odoo-operator.bemade.org/release: "{{ .Release.Revision }}"
    spec:
      affinity:
        {{- toYaml .Values.operator.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.operator.tolerations | nindent 8}}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .domain }}
        {{- end }}
      serviceAccountName: odoo-operator
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.operator.image }}
          imagePullPolicy: {{ .Values.operator.imagePullPolicy | default "Always" }}
          command: ["/manager"]
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
            - --postgres-clusters-secret={{ .Values.postgresClustersSecretRef.name }}
            - --default-odoo-image={{ .Values.defaults.odooImage }}
            - --default-storage-class={{ .Values.defaults.storageClass }}
            - --default-storage-size={{ .Values.defaults.storageSize }}
            {{- if .Values.defaults.ingressClass }}
            - --default-ingress-class={{ .Values.defaults.ingressClass }}
            {{- end }}
            {{- if .Values.defaults.ingressIssuer }}
            - --default-ingress-issuer={{ .Values.defaults.ingressIssuer }}
            {{- end }}
            {{- if .Values.defaults.postgresCluster }}
            - --default-postgres-cluster={{ .Values.defaults.postgresCluster }}
            {{- end }}
            {{- if .Values.defaults.resources }}
            - --default-resources={{ .Values.defaults.resources | toJson }}
            {{- end }}
            {{- if .Values.defaults.affinity }}
            - --default-affinity={{ .Values.defaults.affinity | toJson }}
            {{- end }}
            {{- if .Values.defaults.tolerations }}
            - --default-tolerations={{ .Values.defaults.tolerations | toJson }}
            {{- end }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
