{{- range .Values.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .domain }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {{ printf "{\"auths\": {\"%s\": {\"username\": \"%s\", \"password\": \"%s\", \"auth\": \"%s\", \"email\": \"\"}}}" .domain .username .password (printf "%s:%s" .username .password | b64enc) }}
{{- end }}
