# This rule is not used by the project odoo-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to bemade.bemade.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: odoo-operator
    app.kubernetes.io/managed-by: kustomize
  name: odooinitjob-viewer-role
rules:
- apiGroups:
  - bemade.bemade.org
  resources:
  - odooinitjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bemade.bemade.org
  resources:
  - odooinitjobs/status
  verbs:
  - get
