image: docker.bemade.org/bemade/odoo18.0e
imagePullSecret: docker.bemade.org
adminPassword: abc123
replicas: 1
resources:
  requests:
    cpu: 200m
    memory: 250Mi
  limits:
    cpu: 2000m
    memory: 2Gi
filestore:
  storageSize: 2Gi
  storageClass: standard
ingress:
  hosts:
    - test.odoo.bemade.org
  issuer: letsencrypt-dns
configOptions:
  workers: "2"
  limit_time_real: "600"
  limit_time_cpu: "600"
  addons_path: "/mnt/extra-addons,/mnt/enterprise-addons"

