apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pg-clusters
  namespace: odoo-operator
stringData:
  clusters.yaml: |
    cnpg:
      adminPassword: SdN80SHoRwWz5YA5OYqaoie4QE6YGSYaeYYmymNMrSXuMf9iiEp7OvxarHTEt32P
      adminUser: postgres
      host: database-cluster-rw.database.svc.cluster.local
      port: 5432
    postgres:
      adminPassword: testpassword
      adminUser: postgres
      default: true
      host: postgres.postgres.svc.cluster.local
      port: 5432
